import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.sql.Connection;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class kamar extends javax.swing.JInternalFrame {
    private PreparedStatement stat;
    private ResultSet rs;
    private String filename;


    /**
     * Creates new form dashboardu
     */
    public kamar() {
//        kosong();
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        table_tersedia();
        no_kamar();
    }
    
    private void table_tersedia(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No Kamar");
        model.addColumn("Harga");
        model.addColumn("Kapasitas");
        model.addColumn("Lantai");
        model.addColumn("Fasilitas");
        model.addColumn("Status");
//        tbl_kamar.setModel(model);
       
        try{
            String sql = "SELECT * FROM kamar";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next())
            {
                model.addRow(new Object[]
                {
                    res.getString(1),
                    res.getString(2),
                    res.getString(3),
                    res.getString(4),
                    res.getString(5),
                    res.getString(6)
                });
            }
                tbl_kamar.setModel(model);
                
        }catch (Exception e){
            
        }
    }
    
    private void no_kamar(){
        int no_kamar = 0;
        int i = 0;
        try{
            String sql = "Select no_kamar from kamar";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                no_kamar = res.getInt("no_kamar");
                int n = no_kamar+1;
                txt_nokamar.setText(Integer.toString(n));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nokamar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbkapasitas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtlantai = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cmbstatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtfasilitas = new javax.swing.JTextArea();
        btn_clear = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        txtcarikamar = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnhapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btndetailkamar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_kamar = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtstatusdetail = new javax.swing.JTextField();
        txtlantaidetail = new javax.swing.JTextField();
        txtkapasitasdetail = new javax.swing.JTextField();
        txthargadetail = new javax.swing.JTextField();
        txtnokamardetail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfasilitasdetail = new javax.swing.JTextArea();
        btnclose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(780, 450));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(700, 450));

        jPanel2.setBackground(new java.awt.Color(174, 226, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(174, 226, 255));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(762, 450));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Kamar");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("No Kamar");

        txt_nokamar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        txtharga.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Kapasitas");

        cbkapasitas.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbkapasitas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Orang", "2 Orang", "3 Orang", "4 Orang" }));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Lantai");

        txtlantai.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setText("Status");

        cmbstatus.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersedia", "Terisi" }));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Fasilitas");

        txtfasilitas.setColumns(20);
        txtfasilitas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtfasilitas.setRows(5);
        jScrollPane3.setViewportView(txtfasilitas);

        btn_clear.setBackground(new java.awt.Color(153, 204, 255));
        btn_clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-reset-25.png"))); // NOI18N
        btn_clear.setText("RESET");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(204, 204, 255));
        btnsimpan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-download-25.png"))); // NOI18N
        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        txtcarikamar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtcarikamar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcarikamarKeyReleased(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-25.png"))); // NOI18N

        btnhapus.setBackground(new java.awt.Color(255, 153, 153));
        btnhapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trash-25.png"))); // NOI18N
        btnhapus.setText("HAPUS\n");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(204, 204, 255));
        btn_edit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-create-25.png"))); // NOI18N
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btndetailkamar.setBackground(new java.awt.Color(204, 204, 255));
        btndetailkamar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndetailkamar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-detail-25.png"))); // NOI18N
        btndetailkamar.setText("DETAIL");
        btndetailkamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetailkamarActionPerformed(evt);
            }
        });

        tbl_kamar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tbl_kamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_kamar.setSelectionBackground(new java.awt.Color(153, 51, 255));
        tbl_kamar.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tbl_kamar.setShowGrid(false);
        tbl_kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kamarMouseClicked(evt);
            }
        });
        tbl_kamar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_kamarPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_kamar);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btndetailkamar)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nokamar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnsimpan)))
                        .addGap(44, 44, 44)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cbkapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtlantai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear))
                        .addGap(54, 54, 54)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel27)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cmbstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(47, 47, 47)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtcarikamar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndetailkamar)
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nokamar)
                            .addComponent(cmbstatus)
                            .addComponent(cbkapasitas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtlantai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_clear)
                            .addComponent(btnsimpan)
                            .addComponent(txtcarikamar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kamar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(174, 226, 255));

        kGradientPanel2.setkEndColor(new java.awt.Color(174, 226, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 204, 204));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("Detail Kamar");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("No Kamar ");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("Harga");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Kapasitas");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Lantai");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Status");

        txtstatusdetail.setEditable(false);
        txtstatusdetail.setBackground(new java.awt.Color(255, 255, 255));
        txtstatusdetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtstatusdetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstatusdetail.setEnabled(false);

        txtlantaidetail.setEditable(false);
        txtlantaidetail.setBackground(new java.awt.Color(255, 255, 255));
        txtlantaidetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtlantaidetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtlantaidetail.setEnabled(false);

        txtkapasitasdetail.setEditable(false);
        txtkapasitasdetail.setBackground(new java.awt.Color(255, 255, 255));
        txtkapasitasdetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtkapasitasdetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtkapasitasdetail.setEnabled(false);

        txthargadetail.setEditable(false);
        txthargadetail.setBackground(new java.awt.Color(255, 255, 255));
        txthargadetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txthargadetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txthargadetail.setEnabled(false);
        txthargadetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargadetailActionPerformed(evt);
            }
        });

        txtnokamardetail.setEditable(false);
        txtnokamardetail.setBackground(new java.awt.Color(255, 255, 255));
        txtnokamardetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtnokamardetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnokamardetail.setEnabled(false);
        txtnokamardetail.setMargin(new java.awt.Insets(0, 0, 2, 0));
        txtnokamardetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnokamardetailActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Fasilitas");

        txtfasilitasdetail.setEditable(false);
        txtfasilitasdetail.setBackground(new java.awt.Color(255, 255, 255));
        txtfasilitasdetail.setColumns(20);
        txtfasilitasdetail.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtfasilitasdetail.setRows(5);
        txtfasilitasdetail.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfasilitasdetail.setEnabled(false);
        jScrollPane2.setViewportView(txtfasilitasdetail);

        btnclose.setBackground(new java.awt.Color(102, 153, 255));
        btnclose.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-close-30.png"))); // NOI18N
        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/undraw_No_data_re_kwbl-removebg-preview (1).png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnokamardetail, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthargadetail))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(txtstatusdetail)
                                    .addComponent(txtlantaidetail)
                                    .addComponent(txtkapasitasdetail, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(btnclose)
                        .addGap(27, 27, 27))))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclose))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtnokamardetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txthargadetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtkapasitasdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtlantaidetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtstatusdetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Detail", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO kamar(no_kamar, harga, kapasitas, lantai, fasilitas, status) VALUES ('"+txt_nokamar.getText()+"','"+txtharga.getText()+"',"
                    + "'"+cbkapasitas.getSelectedItem()+"','"+txtlantai.getText()+"','"+txtfasilitas.getText()+"',"
                    + "'"+cmbstatus.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            no_kamar();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Data Tidak Tersimpan");
        }
        table_tersedia();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM kamar WHERE no_kamar = '"+txt_nokamar.getText()+"'";
            java.sql.Connection conn = (Connection)Config.configDB();
            Statement st = conn.createStatement();
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Yakin ingin menghapus data ini?", 
                    "Konfirmasi Hapus", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
            int row = st.executeUpdate(sql);
            if (row==1) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
            conn.close();
            }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        table_tersedia();

//        kosong();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void tbl_kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kamarMouseClicked
        // TODO add your handling code here:
        int baris = tbl_kamar.rowAtPoint(evt.getPoint());
        String no_kamar = tbl_kamar.getValueAt(baris, 0).toString();
        txt_nokamar.setText(no_kamar);
        txt_nokamar.disable();
        if(tbl_kamar.getValueAt(baris, 1)==null){
            txtharga.setText("");
        }else{
            txtharga.setText(tbl_kamar.getValueAt(baris, 1).toString());
        }
        if(tbl_kamar.getValueAt(baris, 2)==null){
            cbkapasitas.setSelectedItem(this);
        }else{
            cbkapasitas.setSelectedItem(tbl_kamar.getValueAt(baris, 2).toString());
        }
        if(tbl_kamar.getValueAt(baris, 3)==null){
            txtlantai.setText("");
        }else{
            txtlantai.setText(tbl_kamar.getValueAt(baris, 3).toString());
        }
        if(tbl_kamar.getValueAt(baris, 4)==null){
            txtfasilitas.setText("");
        }else{
            txtfasilitas.setText(tbl_kamar.getValueAt(baris, 4).toString());
        }
        if(tbl_kamar.getValueAt(baris, 5)==null){
            cmbstatus.setSelectedItem(this);
        }else{
            cmbstatus.setSelectedItem(tbl_kamar.getValueAt(baris, 5).toString());
        }
    }//GEN-LAST:event_tbl_kamarMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "UPDATE kamar "
                    + "SET harga = '"+txtharga.getText()+"', kapasitas = '"
                    +cbkapasitas.getSelectedItem()+"', lantai = '"
                    +txtlantai.getText()+"', fasilitas = '"
                    +txtfasilitas.  getText()+"', status = '"
                    +cmbstatus.getSelectedItem()
                    +"'WHERE no_kamar = '"+txt_nokamar.getText()+"'";
            java.sql.Connection conn  = (Connection)Config.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Di Ubah");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal");
        }
        table_tersedia();
//        kosong();
    }//GEN-LAST:event_btn_editActionPerformed

    private void txtcarikamarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarikamarKeyReleased
        // TODO add your handling code here:
        DefaultTableModel obj = (DefaultTableModel) tbl_kamar.getModel();
        TableRowSorter<DefaultTableModel> obj1 = new TableRowSorter<>(obj);
        tbl_kamar.setRowSorter(obj1);
        obj1.setRowFilter(RowFilter.regexFilter(txtcarikamar.getText()));
    }//GEN-LAST:event_txtcarikamarKeyReleased

    private void btndetailkamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetailkamarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbl = (DefaultTableModel)tbl_kamar.getModel();
        String no_kamar = tbl.getValueAt(tbl_kamar.getSelectedRow(), 0).toString();
        jTabbedPane1.setSelectedIndex(1);
        try{
            Statement st = (Statement)Config.configDB().createStatement();
            ResultSet rs = st.executeQuery("Select * from kamar where no_kamar = '" + no_kamar + "'");
            if(rs.next()){
                txtnokamardetail.setText(rs.getString(1));
                txthargadetail.setText(rs.getString(2));
                txtkapasitasdetail.setText(rs.getString(3));
                txtlantaidetail.setText(rs.getString(4));
                txtfasilitasdetail.setText(rs.getString(5));
                txtstatusdetail.setText(rs.getString(6));
            }else{
                JOptionPane.showMessageDialog(null, no_kamar);
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btndetailkamarActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void txthargadetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargadetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargadetailActionPerformed

    private void txtnokamardetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnokamardetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnokamardetailActionPerformed

    private void tbl_kamarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_kamarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_kamarPropertyChange

    private void kosong(){
        txt_nokamar.enable();
        txtharga.setText(null);
        txtfasilitas.setText(null);
        txt_nokamar.setText(null);
        cbkapasitas.setSelectedItem(this);
        txtlantai.setText(null);
//        cblantai.setSelectedItem(this);
        cmbstatus.setSelectedItem(this);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndetailkamar;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cbkapasitas;
    private javax.swing.JComboBox<String> cmbstatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTable tbl_kamar;
    private javax.swing.JTextField txt_nokamar;
    private javax.swing.JTextField txtcarikamar;
    private javax.swing.JTextArea txtfasilitas;
    private javax.swing.JTextArea txtfasilitasdetail;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthargadetail;
    private javax.swing.JTextField txtkapasitasdetail;
    private javax.swing.JTextField txtlantai;
    private javax.swing.JTextField txtlantaidetail;
    private javax.swing.JTextField txtnokamardetail;
    private javax.swing.JTextField txtstatusdetail;
    // End of variables declaration//GEN-END:variables
}


