
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.StatementImpl;
import com.toedter.calendar.demo.DateChooserPanel;
import java.text.SimpleDateFormat;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.Locale;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class penghuni extends javax.swing.JInternalFrame {

    /**
     * Creates new form dashboardu
     */
    String nik;
    public penghuni() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        datatable();
        cmbNoKamar();
        cmbNoKamarEdit();
        tampil_tanggal ();
//        cmbNoKamarDetail();
    }
    
    private void datatable() {
        DefaultTableModel tbl=new DefaultTableModel();
        tbl.addColumn("NIK");
        tbl.addColumn("Nama");
        tbl.addColumn("Alamat");
        tbl.addColumn("No HP");
        tbl.addColumn("Tanggal Lahir");
        tbl.addColumn("Registrasi");
        tbl.addColumn("No Kamar");
        tblpenghuni.setModel(tbl);
        try{
            Statement statement=(Statement)Config.configDB().createStatement();
            ResultSet res=statement.executeQuery("SELECT * FROM penghuni");
            while(res.next())
            {
                tbl.addRow(new Object[]{
                res.getString("id_penghuni"),
                res.getString("nama"),
                res.getString("nik"),
                res.getString("alamat"),
                res.getString("no_handphone"),
                res.getString("tanggal_lahir"),
                res.getString("registrasi"),
                res.getString("no_kamar")
            }); 
            tblpenghuni.setModel(tbl);
            }
        }catch (Exception e) {
//                JOptionPane.showMessageDialog(rootPane, "salah");
    }
}
    
    public void tampil_tanggal () {
//        jLabelregister.setText(tanggal);
    }
    
    public void cmbNoKamar(){
        try{
            Statement st = (Statement)Config.configDB().createStatement();
            ResultSet res = st.executeQuery("Select no_kamar from kamar where status = \"Tersedia\";");
            while(res.next())
            {
                cbnokamar.addItem(res.getString("no_kamar"));
            }
            res.last();
            int jumlahkamar = res.getRow();
            res.first();
        }catch (SQLException e){
            
        }
    }
    
    public void cmbNoKamarEdit(){
        try{
            Statement st = (Statement)Config.configDB().createStatement();
            ResultSet res = st.executeQuery("Select no_kamar from kamar where status = \"Tersedia\";");
            while(res.next())
            {
                cbnokamaredit.addItem(res.getString("no_kamar"));
            }
            res.last();
            int jumlahkamar = res.getRow();
            res.first();
        }catch (SQLException e){
            
        }
    }
    
    private void no_kamar(){
        int no_kamar = 1;
        int i = 0;
        try{
            String sql = "Select no_kamar from kamar";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while(res.next()){
                no_kamar = res.getInt("no_kamar");
                int n = no_kamar+1;
                cbnokamar.setToolTipText(Integer.toString(n));
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
    }
}
//    public void cmbNoKamarDetail(){
//        try{
//            Statement st = (Statement)Config.configDB().createStatement();
//            ResultSet res = st.executeQuery("SELECT * FROM kamar");
//            while(res.next())
//            {
//                cbnokamarDETAIL.add(res.getString("no_kamar"));
//            }
//            res.last();
//            int jumlahkamar = res.getRow();
//            res.first();
//        }catch (SQLException e){
//            
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtnik = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txttanggallahir = new com.toedter.calendar.JDateChooser();
        jLabelregister = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtalamat = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtnohp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        cbnokamar = new javax.swing.JComboBox<>();
        txt_cari = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpenghuni = new javax.swing.JTable();
        btnsave = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel9 = new javax.swing.JLabel();
        txtnikedit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnohpedit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnamaedit = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txttanggallahiredit = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        cbnokamaredit = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtalamatedit = new javax.swing.JTextArea();
        btn_canceledit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtregistrasiedit = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(780, 450));

        jPanel4.setBackground(new java.awt.Color(174, 226, 255));

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(174, 226, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Data Penghuni");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setText("NIK");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel26.setText("Alamat");

        txtnik.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnikActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel27.setText("Tanggal Lahir");

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel28.setText("Registrasi");

        jLabelregister.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabelregister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtalamat.setColumns(20);
        txtalamat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtalamat.setRows(5);
        jScrollPane5.setViewportView(txtalamat);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Nama");

        txtnama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel30.setText("No Handphone");

        txtnohp.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel29.setText("No Kamar");

        cbnokamar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cbnokamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- pilih kamar --" }));
        cbnokamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnokamarActionPerformed(evt);
            }
        });

        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-search-25.png"))); // NOI18N

        tblpenghuni.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tblpenghuni.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama", "Alamat", "No HP", "No Kamar", "Aksi"
            }
        ));
        tblpenghuni.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblpenghuniAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblpenghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenghuniMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpenghuni);

        btnsave.setBackground(new java.awt.Color(204, 204, 255));
        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-download-25.png"))); // NOI18N
        btnsave.setText("SIMPAN");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btn_cancel.setBackground(new java.awt.Color(102, 153, 255));
        btn_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_cancel.setText("CANCEL");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btnhapus.setBackground(new java.awt.Color(255, 153, 153));
        btnhapus.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-trash-25.png"))); // NOI18N
        btnhapus.setText("HAPUS");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        btnedit.setBackground(new java.awt.Color(204, 204, 255));
        btnedit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-create-25.png"))); // NOI18N
        btnedit.setText("EDIT");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(txtnama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnsave))
                .addGap(25, 25, 25)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(txttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28)
                            .addComponent(jLabelregister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbnokamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(163, 163, 163))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_cancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhapus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txttanggallahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelregister, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbnokamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsave))
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnhapus)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Penghuni", jPanel4);

        jPanel1.setBackground(new java.awt.Color(174, 226, 255));

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 204, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(174, 226, 255));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setText("NIK");

        txtnikedit.setEditable(false);
        txtnikedit.setBackground(new java.awt.Color(255, 255, 255));
        txtnikedit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtnikedit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtnikedit.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel16.setText("No Handphone");

        txtnohpedit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Registrasi");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setText("Nama");

        txtnamaedit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtnamaedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaeditActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Tanggal Lahir");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel18.setText("No Kamar");

        cbnokamaredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnokamareditActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setText("Alamat");

        txtalamatedit.setColumns(20);
        txtalamatedit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtalamatedit.setRows(5);
        jScrollPane3.setViewportView(txtalamatedit);

        btn_canceledit.setBackground(new java.awt.Color(204, 204, 255));
        btn_canceledit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_canceledit.setText("CANCEL");
        btn_canceledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_canceleditActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(204, 204, 255));
        btnupdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        txtregistrasiedit.setEditable(false);
        txtregistrasiedit.setBackground(new java.awt.Color(255, 255, 255));
        txtregistrasiedit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtregistrasiedit.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtregistrasiedit.setEnabled(false);

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addComponent(txtnamaedit)
                                .addGap(85, 85, 85))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtnikedit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)))
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txttanggallahiredit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(cbnokamaredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(125, 125, 125))
                            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtnohpedit, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(txtregistrasiedit, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_canceledit)
                .addGap(18, 18, 18)
                .addComponent(btnupdate)
                .addGap(28, 28, 28))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnikedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnohpedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtregistrasiedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtnamaedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbnokamaredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttanggallahiredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_canceledit)
                    .addComponent(btnupdate))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Edit", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaeditActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String Nama = txtnamaedit.getText();
        String Alamat = txtalamatedit.getText();
        String NoHandphone = txtnohpedit.getText();
        String NoKamar = (String) cbnokamaredit.getSelectedItem();
        try {
            Statement Statement= (Statement)Config.configDB().createStatement();
            Statement.executeUpdate("UPDATE penghuni SET Nama='"
                + txtnamaedit.getText() + "', Alamat ='"
                + txtalamatedit.getText() + "', No_Handphone= '" +txtnohpedit.getText() 
                    + "', No_kamar = '" + cbnokamaredit.getSelectedItem() + "' WHERE penghuni.NIK= '" + nik + "'");
            Statement.close();
            JOptionPane.showMessageDialog(null,"Data Berhasil di Edit");
            txtnikedit.setText("");
            txtnamaedit.setText("");
            txtalamatedit.setText("");
            txtnohpedit.setText("");
            txttanggallahiredit.setToolTipText("");
            txtregistrasiedit.setToolTipText("");
            cbnokamaredit.setToolTipText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal" + e.getMessage());
        } 
        datatable();
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbll = (DefaultTableModel)tblpenghuni.getModel();
        try{
            String sql = "DELETE FROM penghuni WHERE NIK= '"+nik+"'";
            java.sql.Connection conn = (Connection)Config.configDB();
            Statement st = conn.createStatement();
            int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                int row = st.executeUpdate(sql);
                if (row==1) {
                    JOptionPane.showMessageDialog(this, "data berhasil dihapus");
                    conn.close();
                }
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        datatable();
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbll = (DefaultTableModel)tblpenghuni.getModel();
        jTabbedPane1.setSelectedIndex(1);
        try {
            Statement statement = (Statement)Config.configDB().createStatement();
            ResultSet res = statement.executeQuery("Select * from penghuni where NIK = '" + nik + "'");
            if (res.next()) {
                txtnikedit.setText(res.getString("NIK"));
                txtnamaedit.setText(res.getString("Nama"));
                txtalamatedit.setText(res.getString("Alamat"));
                txtnohpedit.setText(res.getString("No_Handphone"));
                txttanggallahiredit.setDate(res.getDate("Tanggal_lahir"));
                txtregistrasiedit.setText(res.getString("Registrasi"));
                cbnokamaredit.setSelectedItem(res.getString("No_kamar"));
            }else{
                JOptionPane.showMessageDialog(null, nik);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void btn_canceleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_canceleditActionPerformed
        // TODO add your handling code here:
        txtnikedit.setText("");
        txtnamaedit.setText("");
        txtalamatedit.setText("");
        txtnohpedit.setText("");
        txttanggallahiredit.setToolTipText("");
        txtregistrasiedit.setToolTipText("");
        cbnokamaredit.setSelectedItem("");
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_canceleditActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        // TODO add your handling code here:
        DefaultTableModel ob =(DefaultTableModel) tblpenghuni.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(ob);
        tblpenghuni.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(txt_cari.getText()));
    }//GEN-LAST:event_txt_cariKeyReleased

    private void tblpenghuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpenghuniMouseClicked
        // TODO add your handling code here:
        int baris = tblpenghuni.rowAtPoint(evt.getPoint());
        nik = tblpenghuni.getValueAt(baris, 0).toString();
       
//        if(tblpenghuni.getValueAt(baris, 1)==null){
//            txtnama.setText("");
//        }else{
//            txtnama.setText(tblpenghuni.getValueAt(baris, 1).toString());
//        }
//        if(tblpenghuni.getValueAt(baris, 2)==null){
//            txtalamat.setText("");
//        }else{
//            txtalamat.setText(tblpenghuni.getValueAt(baris, 2).toString());
//        }
//        if(tblpenghuni.getValueAt(baris, 3)==null){
//            txtnohp.setText("");
//        }else{
//            txtnohp.setText(tblpenghuni.getValueAt(baris, 3).toString());
//        }
//        if(tblpenghuni.getValueAt(baris, 4)==null){
//            txttanggallahir.getDate().toString();
//        }else{
//            txttanggallahir.setDateFormatString(tblpenghuni.getValueAt(baris, 4).toString());
//        }
//        if(tblpenghuni.getValueAt(baris, 5)==null){
//            txtregistrasi.getDate().toString();
//        }else{
//            txtregistrasi.setDateFormatString(tblpenghuni.getValueAt(baris, 5).toString());
//        }
//        if(tblpenghuni.getValueAt(baris, 6)==null){
//            cbnokamar.setSelectedItem(this);
//        }else{
//            cbnokamar.setSelectedItem(tblpenghuni.getValueAt(baris, 6).toString());
//        }
    }//GEN-LAST:event_tblpenghuniMouseClicked

    private void tblpenghuniAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblpenghuniAncestorAdded
        // TODO add your handling code here:
//        void getnokamar (){
//        try {
//            Statement statement = (Statement)Config.configDB().createStatement();
//            ResultSet res = statement.executeQuery("Select No_kamar from kamar where status= 'kosong'");
//            while (res.next()) {
//                cbnokamar.addItem(res.getString("No_kamar"));
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, e);
//        }
//    }
    }//GEN-LAST:event_tblpenghuniAncestorAdded

    private void cbnokamareditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnokamareditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnokamareditActionPerformed

    private void txtnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnikActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        txtnikedit.setText("");
        txtnamaedit.setText("");
        txtalamatedit.setText("");
        txtnohpedit.setText("");
        txttanggallahiredit.setToolTipText("");
        txtregistrasiedit.setToolTipText("");
        cbnokamaredit.setSelectedItem("");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        java.util.Date tglsekarang = new java.util.Date();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = sdf.format(tglsekarang);
        System.out.println(jLabelregister.getText());
        String NIK = txtnik.getText();
        String Nama = txtnama.getText();
        String Alamat = txtalamat.getText();
        String NoHandphone = txtnohp.getText();
        String TanggalLahir = sdf.format(txttanggallahir.getDate()).toString();
        String NoKamar = (String) cbnokamar.getSelectedItem();
        try {
            Statement Statement= (Statement)Config.configDB().createStatement();
            Statement.executeUpdate
        ("INSERT INTO penghuni VALUES ('" + NIK + "', '" + Nama + "', '" + Alamat + "', '" 
                + NoHandphone + "', '" + TanggalLahir + "', '" + tanggal + "', '" + NoKamar + "');");
            Statement.close();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            txtnik.setText("");
            txtnama.setText("");
            txtalamat.setText("");
            txtnohp.setText("");
            txttanggallahir.setToolTipText("");
            jLabelregister.setText("");
            cbnokamar.getSelectedItem();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal!");
        }
        datatable();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void cbnokamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnokamarActionPerformed
        // TODO add your handling code here:
//        String sql = ""
    }//GEN-LAST:event_cbnokamarActionPerformed

    void getnokamar (){
        try {
            Statement statement = (Statement)Config.configDB().createStatement();
            ResultSet res = statement.executeQuery("Select No_kamar from kamar where status= 'kosong'");
            while (res.next()) {
                cbnokamar.addItem(res.getString("No_kamar"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_canceledit;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbnokamar;
    private javax.swing.JComboBox<String> cbnokamaredit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelregister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JTable tblpenghuni;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextArea txtalamat;
    private javax.swing.JTextArea txtalamatedit;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamaedit;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txtnikedit;
    private javax.swing.JTextField txtnohp;
    private javax.swing.JTextField txtnohpedit;
    private javax.swing.JTextField txtregistrasiedit;
    private com.toedter.calendar.JDateChooser txttanggallahir;
    private com.toedter.calendar.JDateChooser txttanggallahiredit;
    // End of variables declaration//GEN-END:variables
}
